version: '2'
services:

  # squid_agent:
  #   image: krkr/squid
  #   network_mode: host
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /home/ubuntu/compose:/app/compose
  #   command: -join https://squid.blurb.space
  #   restart: always

  telegraf:
    image: krkr/telegraf
    container_name: o_metrics
    network_mode: host
    environment:
      - OVH_INFLUXDB_URL
      - OPENTSDB_URL
      - OPENTSDB_USER
      - OPENTSDB_PASSWORD
      - OVH_METRICS_URL
      - OVH_METRICS_READ_TOKEN
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
    restart: always
    command:
      -input-filter cpu:disk:diskio:kernel:mem:processes:swap:system:docker:net
      -output-filter opentsdb_http
